default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: railsondocker_development

test:
  <<: *default
  database: railsondocker_test
